<<<<<<< HEAD
# Generated by Django 4.2.23 on 2025-11-05 18:12
=======
# Generated by Django 4.2.23 on 2025-09-30 21:40
>>>>>>> origin/main

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("memes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("humor_score", models.IntegerField()),
                ("cultural_score", models.IntegerField()),
                ("creativity_score", models.IntegerField()),
                ("comment", models.TextField(blank=True)),
                ("user_id", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="memes.meme",
                    ),
                ),
            ],
        ),
    ]
