# Generated by Django 4.2.23 on 2025-08-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("caption", models.TextField()),
                ("created_by", models.CharField(max_length=10)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("macro", "Macro"),
                            ("tweet", "Tweet"),
                            ("gif", "GIF"),
                            ("sticker", "Sticker"),
                        ],
                        max_length=10,
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
