# Generated by Django 4.2.23 on 2025-11-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("memes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meme",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="memes.memetemplate",
            ),
        ),
    ]
