# Generated by Django 4.2.23 on 2025-10-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meme",
            name="creativity_avg",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meme",
            name="cultural_avg",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meme",
            name="humor_avg",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meme",
            name="total_votes",
            field=models.IntegerField(default=0),
        ),
    ]
