# Generated by Django 4.2.23 on 2025-11-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memes", "0002_alter_meme_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="meme",
            name="ai_model",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
