# Generated by Django 4.2.23 on 2025-10-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memes", "0002_meme_creativity_avg_meme_cultural_avg_meme_humor_avg_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meme",
            name="creativity_avg",
        ),
        migrations.RemoveField(
            model_name="meme",
            name="cultural_avg",
        ),
    ]
