# Generated by Django 4.2.23 on 2025-11-20 00:40

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("memes", "0003_meme_ai_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meme",
            name="ai_model",
        ),
        migrations.AlterField(
            model_name="meme",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="meme",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memes",
                to="memes.memetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="memetemplate",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
