# Generated by Django 4.2.23 on 2025-11-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memes", "0004_remove_meme_ai_model_alter_meme_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="meme",
            name="topic",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="memetemplate",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
