# Generated by Django 4.2.23 on 2025-11-20 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("memes", "0005_alter_category_name_alter_meme_topic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meme",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memes",
                to="memes.memetemplate",
            ),
        ),
    ]
