# Generated by Django 4.2.23 on 2025-12-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memes", "0006_alter_meme_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
