# Generated by Django 4.2.23 on 2025-12-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memes", "0007_weeklytopic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meme",
            name="creativity_avg",
        ),
        migrations.RemoveField(
            model_name="meme",
            name="cultural_avg",
        ),
        migrations.RemoveField(
            model_name="meme",
            name="humor_avg",
        ),
    ]
