# Generated by Django 4.2.23 on 2025-12-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memes", "0008_remove_meme_creativity_avg_remove_meme_cultural_avg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meme",
            name="rating",
            field=models.FloatField(default=1000),
        ),
    ]
